emotion_detection/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('frontend/', include('frontend.urls')),
    path('admin/', admin.site.urls),
]

frontend/urls.py
from django.urls import path
from . import views

app_name = 'frontend'
urlpatterns = [
	path('', views.index, name='index'),
	path('result/', views.result, name='result'),
]

frontend/models.py
from django.db import models

# Create your models here.
class UserInput(models.Model):
	user_text = models.CharField(max_length=500)
	def __str__(self):
		return self.user_text

machine_learning/models.py
from django.db import models

# Create your models here.

frontend/views.py
from django.shortcuts import render, get_object_or_404
from .models import UserInput
import sys

#sys.path.append('frontend/ML')
from frontend.emotion_analyzer import emo_analyze

# Create your views here.
def index(request):
	return render(request, 'frontend/index.html')

def result(request):	
	user_input = request.POST.get('message')
	probabilities = emo_analyze(user_input)
	#print('Text is: ' + user_input)
	#print(probabilities)
	#labels =
	values = probabilities.values.tolist()[0]
	args = {'text': user_input, 'anger': values[0]*100, 'disgust': values[1]*100, 'fear': values[2]*100, 'guilt': values[3]*100, 'joy': values[4]*100, 'sadness':values[5]*100, 'shame': values[6]*100}
	#print(args)
	return render(request,'frontend/result.html', args)

machine_learning/views.py
from django.shortcuts import render

# Create your views here.

frontend/templates/frontend/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Emotion Detection</title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'form.css' %}" >
    </head>
    <body >
        <!--"-->
        <div class="container">
            <div id="form-main">
                <div id="form-div">
                    <form class="montform" action="{% url 'frontend:result' %}" id="reused_form" method="POST">{% csrf_token %}
                        <p class="text">
                            <textarea name="message" class="feedback-input" id="text" name="text_to_analyze" placeholder="Enter text to be analyzed"></textarea>
                        </p>
                        <div class="submit">
                            <button type="submit" class="button-blue" name='submit_btn'>SUBMIT</button>
                            <div class="ease"></div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </body>
</html>

frontend/templates/frontend/result.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Emotion Detection</title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'form.css' %}" >
        <!--<script src="{% static 'form.js' %} style="width:100%; height:100%;"></script> -->
    </head>
    <body >
        <div class="container">
            <div id="form-main">
                <div id="form-div">
                    <div id="success_message">
                        <div class="slidecontainer">               
                        <h3>TEXT:</h3>
                        <h3> {{text}} </h3>
                        <label style="text-align:left;display:block;" for="anger" class="margin">Anger:</label>
                        	<input type="range" min="0" max="100" value="{{anger}}" class="slider" id="anger" name="anger"><br/>
                        <label style="text-align:left;display:block;" for="disgust" class="margin">Disgust:</label>
                        	<input type="range" min="0" max="100" value="{{disgust}}" class="slider" id="disgust" name="disgust"><br/>
                        <label style="text-align:left;display:block;" for="fear" class="margin">Fear:</label>
                        	<input type="range" min="0" max="100" value="{{fear}}" class="slider" id="fear" name="fear"><br/>
                        <label style="text-align:left;display:block;" for="guilt" class="margin">Guilt:</label>
                        	<input type="range" min="0" max="100" value="{{guilt}}" class="slider" id="guilt" name="guilt"> <br/> 
                        <label style="text-align:left;display:block;" for="joy" class="margin">Joy:</label>	
                        	<input type="range" min="0" max="100" value="{{joy}}" class="slider" id="joy" name="joy"> <br/>
                        <label style="text-align:left;display:block;" for="sadness" class="margin">Sadness:</label>
                        	<input type="range" min="0" max="100" value="{{sadness}}" class="slider" id="sadness" name="sadness"> <br/> 
                        <label style="text-align:left;display:block;" for="shame" class="margin">Shame:</label>
                        	<input type="range" min="0" max="100" value="{{shame}}" class="slider" id="shame" name="shame"> <br/> 
                     </div>
                </div>
            </div>
        </div>
    </div>
                            
    </body>
</html>